// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7nEnilAFbyivRon1VjoeVvNZR-qpKw7s',
    appId: '1:286785617749:web:f4da5b9df838c5ca6179dc',
    messagingSenderId: '286785617749',
    projectId: 'flutter-login-da31e',
    authDomain: 'flutter-login-da31e.firebaseapp.com',
    storageBucket: 'flutter-login-da31e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1TfoFPmHBdS3uj1KQLlZZ3_yhf-H93E',
    appId: '1:286785617749:android:51f17daa662232866179dc',
    messagingSenderId: '286785617749',
    projectId: 'flutter-login-da31e',
    storageBucket: 'flutter-login-da31e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96AIczp7gJ5pCNbpdvjOlfuETR56eo-I',
    appId: '1:286785617749:ios:bd0f6cea032713166179dc',
    messagingSenderId: '286785617749',
    projectId: 'flutter-login-da31e',
    storageBucket: 'flutter-login-da31e.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );
}
